repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: requirements-txt-fixer
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: [ --fix, "--line-length=120" ]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: locale|kickstarter-announcement.md|coreapi-0.1.1.js
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [ "--ignore=B6" ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: python
        types: [ python ]
        args: [ '--exclude', '**/tests/*.py' ]
  - repo: local
    hooks:
      - id: run-coverage
        name: Run Coverage
        entry: poetry run python scripts/run_coverage.py
        language: python
        pass_filenames: false
        stages: [ commit ]
