# Generated by Django 5.0.7 on 2024-07-29 01:57

import common.models.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "username",
                    models.CharField(max_length=64, unique=True, verbose_name="用户名"),
                ),
                (
                    "mobile",
                    models.CharField(max_length=64, unique=True, verbose_name="手机号"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                (
                    "last_login_at",
                    models.DateTimeField(null=True, verbose_name="上次登陆时间"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="是否是管理员"),
                ),
                ("created_name", models.CharField(max_length=32)),
                ("updated_name", models.CharField(default="", max_length=32)),
                (
                    "created",
                    common.models.base.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_created",
                        to="user.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated",
                    common.models.base.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_updated",
                        to="user.user",
                        verbose_name="上次修改人",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
