# Generated by Django 5.0.7 on 2024-07-29 01:57

import common.models.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("context", models.JSONField(null=True, verbose_name="上下文")),
                ("exception_stack", models.TextField(verbose_name="异常堆栈")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                ("browser", models.CharField(default="", max_length=128)),
                ("os", models.CharField(default="", max_length=128)),
                ("device", models.CharField(default="", max_length=128)),
                (
                    "login_result",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "成功"), (1, "失败")], verbose_name="登陆结果"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="", max_length=128, verbose_name="登陆失败原因"
                    ),
                ),
                (
                    "user",
                    common.models.base.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_login_log_user",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                ("browser", models.CharField(default="", max_length=128)),
                ("os", models.CharField(default="", max_length=128)),
                ("device", models.CharField(default="", max_length=128)),
                (
                    "api",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="请求地址"
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="请求开始时间")),
                ("end_at", models.DateTimeField(verbose_name="请求响应时间")),
                ("duration", models.IntegerField(verbose_name="响应耗时(毫秒)")),
                (
                    "status_code",
                    models.IntegerField(db_index=True, verbose_name="状态码"),
                ),
                ("response", models.JSONField(null=True, verbose_name="返回值")),
                ("method", models.CharField(max_length=32, verbose_name="请求方式")),
                ("query_params", models.JSONField(null=True)),
                ("body", models.JSONField(null=True, verbose_name="请求体")),
                ("headers", models.JSONField(verbose_name="请求头")),
                (
                    "user",
                    common.models.base.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_operation_log_user",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
